version: "3.8"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: demos-website-prod
